# otel/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3030"

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 80
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: upsert
      - key: service.namespace
        action: upsert
        value: ridgeline

exporters:
  otlphttp/elastic:
    endpoint: ${ELASTIC_OTEL_OTLP_ENDPOINT}
    headers:
      Authorization: "ApiKey ${ELASTIC_OTEL_API_KEY}"
  logging:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"
      level: "detailed"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/elastic, logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/elastic, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/elastic, logging]
